// Generated by CoffeeScript 1.10.0
(function() {
  var Accounts, BankAccounts, Resource,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  BankAccounts = require('./bankaccounts');

  Resource = require('./resource');

  Accounts = (function(superClass) {
    extend(Accounts, superClass);

    function Accounts() {
      return Accounts.__super__.constructor.apply(this, arguments);
    }

    Accounts.prototype.create = function(data) {
      var headers;
      headers = this.authenticator.secureHeaders('post', this.uri());
      return this.request('post', {
        uri: this.uri(),
        headers: headers,
        body: JSON.stringify(data)
      });
    };

    Accounts.prototype.update = function(accountId, data) {
      var headers;
      headers = this.authenticator.secureHeaders('post', this.uri(accountId));
      return this.request('post', {
        uri: this.uri(accountId),
        headers: headers,
        body: JSON.stringify(data)
      });
    };

    Accounts.prototype.bankaccounts = function(accountId) {
      return new BankAccounts(this.host, this.authenticator, this.uri(accountId));
    };

    return Accounts;

  })(Resource);

  module.exports = Accounts;

}).call(this);
