// Generated by CoffeeScript 1.10.0
(function() {
  var BankAccounts, Resource,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Resource = require('./resource');

  BankAccounts = (function(superClass) {
    extend(BankAccounts, superClass);

    function BankAccounts() {
      return BankAccounts.__super__.constructor.apply(this, arguments);
    }

    BankAccounts.prototype.create = function(data) {
      var headers;
      headers = this.authenticator.secureHeaders('post', this.uri());
      return request('post', {
        uri: this.uri(),
        headers: headers,
        body: JSON.stringify(data)
      });
    };

    return BankAccounts;

  })(Resource);

  module.exports = BankAccounts;

}).call(this);
