// Generated by CoffeeScript 1.10.0
(function() {
  var Disputes, Documents, Notes, Offers, Resource,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Documents = require('./documents');

  Notes = require('./notes');

  Offers = require('./offers');

  Resource = require('./resource');

  Disputes = (function(superClass) {
    extend(Disputes, superClass);

    function Disputes() {
      return Disputes.__super__.constructor.apply(this, arguments);
    }

    Disputes.prototype.documents = function(disputeId) {
      return new Documents(this.host, this.authenticator, this.uri(disputeId));
    };

    Disputes.prototype.notes = function(disputeId) {
      return new Notes(this.host, this.authenticator, this.uri(disputeId));
    };

    Disputes.prototype.offers = function(disputeId) {
      return new Offers(this.host, this.authenticator, this.uri(disputeId));
    };

    return Disputes;

  })(Resource);

  module.exports = Disputes;

}).call(this);
