// Generated by CoffeeScript 1.10.0
(function() {
  var Documents, Resource,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Resource = require('./resource');

  Documents = (function(superClass) {
    extend(Documents, superClass);

    function Documents() {
      return Documents.__super__.constructor.apply(this, arguments);
    }

    Documents.prototype.create = function(data) {
      var headers;
      headers = this.authenticator.secureHeaders('post', this.uri());
      return this.request('post', {
        uri: this.uri(),
        headers: headers,
        body: JSON.stringify(data)
      });
    };

    return Documents;

  })(Resource);

  module.exports = Documents;

}).call(this);
