// Generated by CoffeeScript 1.10.0
(function() {
  var API, Accounts, Authenticator, Orders, ShipmentCarriers, Users;

  Accounts = require('./accounts');

  Orders = require('./orders');

  Users = require('./users');

  Authenticator = require('../authenticator');

  ShipmentCarriers = require('./shipmentcarriers');

  API = (function() {
    function API(apiKey, apiSecret, sandbox) {
      this.sandbox = sandbox != null ? sandbox : false;
      this.authenticator = new Authenticator(apiKey, apiSecret);
    }

    API.prototype.armorHost = function() {
      return "https://" + (this.sandbox ? 'sandbox' : 'api') + ".armorpayments.com";
    };

    API.prototype.accounts = function() {
      this._accounts || (this._accounts = new Accounts(this.armorHost(), this.authenticator, ''));
      return this._accounts;
    };

    API.prototype.orders = function(accountId) {
      return new Orders(this.armorHost(), this.authenticator, this.accounts().uri(accountId));
    };

    API.prototype.users = function(accountId) {
      return new Users(this.armorHost(), this.authenticator, this.accounts().uri(accountId));
    };

    API.prototype.shipmentcarriers = function() {
      this._shipmentcarriers || (this._shipmentcarriers = new ShipmentCarriers(this.armorHost(), this.authenticator, ''));
      return this._shipmentcarriers;
    };

    return API;

  })();

  module.exports = API;

}).call(this);
