// Generated by CoffeeScript 1.10.0
(function() {
  var Documents, Notes, Offers, Resource,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Documents = require('./documents');

  Notes = require('./notes');

  Resource = require('./resource');

  Offers = (function(superClass) {
    extend(Offers, superClass);

    function Offers() {
      return Offers.__super__.constructor.apply(this, arguments);
    }

    Offers.prototype.update = function(offerId, data) {
      var headers;
      headers = this.authenticator.secureHeaders('post', this.uri(offerId));
      return this.request('post', {
        uri: this.uri(offerId),
        headers: headers,
        body: JSON.stringify(data)
      });
    };

    Offers.prototype.documents = function(offerId) {
      return new Documents(this.host, this.authenticator, this.uri(offerId));
    };

    Offers.prototype.notes = function(offerId) {
      return new Notes(this.host, this.authenticator, this.uri(offerId));
    };

    return Offers;

  })(Resource);

  module.exports = Offers;

}).call(this);
