// Generated by CoffeeScript 1.10.0
(function() {
  var PaymentInstructions, Resource,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Resource = require('./resource');

  PaymentInstructions = (function(superClass) {
    extend(PaymentInstructions, superClass);

    function PaymentInstructions() {
      return PaymentInstructions.__super__.constructor.apply(this, arguments);
    }

    return PaymentInstructions;

  })(Resource);

  module.exports = PaymentInstructions;

}).call(this);
