// Generated by CoffeeScript 1.10.0
(function() {
  var Resource, ShipmentCarriers,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Resource = require('./resource');

  ShipmentCarriers = (function(superClass) {
    extend(ShipmentCarriers, superClass);

    function ShipmentCarriers() {
      return ShipmentCarriers.__super__.constructor.apply(this, arguments);
    }

    return ShipmentCarriers;

  })(Resource);

  module.exports = ShipmentCarriers;

}).call(this);
