// Generated by CoffeeScript 1.10.0
(function() {
  var Authentications, Resource, Users,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Authentications = require('./authentications');

  Resource = require('./resource');

  Users = (function(superClass) {
    extend(Users, superClass);

    function Users() {
      return Users.__super__.constructor.apply(this, arguments);
    }

    Users.prototype.update = function(userId, data) {
      var headers;
      headers = this.authenticator.secureHeaders('post', this.uri(userId));
      return this.request('post', {
        uri: this.uri(userId),
        headers: headers,
        body: JSON.stringify(data)
      });
    };

    Users.prototype.authentications = function(userId) {
      return new Authentications(this.host, this.authenticator, this.uri(userId));
    };

    return Users;

  })(Resource);

  module.exports = Users;

}).call(this);
