// Generated by CoffeeScript 1.10.0
(function() {
  var Authenticator, crypto;

  crypto = require('crypto');

  Authenticator = (function() {
    function Authenticator(apiKey, apiSecret) {
      this.apiKey = apiKey;
      this.apiSecret = apiSecret;
    }

    Authenticator.prototype.secureHeaders = function(method, uri) {
      return {
        'X-ARMORPAYMENTS-APIKEY': this.apiKey,
        'X-ARMORPAYMENTS-REQUESTTIMESTAMP': this.currentTimestamp(),
        'X-ARMORPAYMENTS-SIGNATURE': this.requestSignature(method, uri)
      };
    };

    Authenticator.prototype.currentTimestamp = function() {
      return (new Date).toISOString().replace(/\.[0-9]+/, '');
    };

    Authenticator.prototype.requestSignature = function(method, uri) {
      var hash;
      hash = crypto.createHash('sha512');
      hash.update(this.apiSecret + ":" + (method.toUpperCase()) + ":" + uri + ":" + (this.currentTimestamp()));
      return hash.digest('hex');
    };

    return Authenticator;

  })();

  module.exports = Authenticator;

}).call(this);
