// Generated by CoffeeScript 1.10.0
(function() {
  var API, Authenticator, exports;

  API = require('./api');

  Authenticator = require('./authenticator');

  exports = module.exports = {};

  exports.API = API;

  exports.Authenticator = Authenticator;

}).call(this);
